# Generated by Django 4.0.1 on 2022-01-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.SlugField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.URLField()),
                ('socials', models.JSONField()),
            ],
        ),
    ]
