# Generated by Django 4.0.1 on 2022-03-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.SlugField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('bio', models.TextField()),
                ('profile_image', models.URLField()),
                ('socials', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPost',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.TextField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_picture', models.URLField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('links', models.JSONField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('speakers', models.ManyToManyField(to='root.Person')),
                ('tags', models.ManyToManyField(blank=True, to='root.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.TextField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='root.Person')),
                ('tags', models.ManyToManyField(blank=True, to='root.Tag')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('episode_links', models.JSONField()),
                ('links_from_guests', models.JSONField()),
                ('transcript', models.JSONField()),
                ('guests', models.ManyToManyField(to='root.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('podcast', 'podcast'), ('webinar', 'webinar'), ('workshop', 'workshop'), ('conf', 'conference')], max_length=8)),
                ('event_link', models.URLField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('speakers', models.ManyToManyField(to='root.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sylabus', models.JSONField()),
                ('partners', models.JSONField()),
                ('registration_link', models.URLField(blank=True, null=True)),
                ('people', models.ManyToManyField(to='root.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.URLField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('links', models.JSONField()),
                ('authors', models.ManyToManyField(to='root.Person')),
            ],
        ),
    ]
