# Generated by Django 4.0.1 on 2022-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('podcast', 'podcast'), ('webinar', 'webinar'), ('workshop', 'workshop'), ('conf', 'conference')], max_length=8)),
                ('event_link', models.URLField()),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('speakers', models.ManyToManyField(to='root.Person')),
            ],
        ),
    ]
