# Generated by Django 4.0.3 on 2022-03-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_book_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='archive',
            field=models.JSONField(null=True),
        ),
    ]
