# Generated by Django 4.0.1 on 2022-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('links', models.JSONField()),
                ('transcript', models.JSONField()),
                ('guests', models.ManyToManyField(to='root.Person')),
            ],
        ),
    ]
