# Generated by Django 4.0.3 on 2022-03-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_podcast_links_from_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='transcript',
            field=models.JSONField(null=True),
        ),
    ]
