# Generated by Django 4.0.1 on 2022-01-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_podcast'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podcast',
            old_name='links',
            new_name='episode_links',
        ),
        migrations.AddField(
            model_name='podcast',
            name='links_from_guests',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
