# Generated by Django 4.0.3 on 2022-03-28 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_alter_podcast_options_alter_tool_icon_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='sylabus',
            new_name='syllabus',
        ),
    ]
