# Generated by Django 4.0.1 on 2022-01-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_rename_links_podcast_episode_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.TextField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
                ('draft', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now_add=True)),
                ('authors', models.ManyToManyField(to='root.Person')),
                ('tags', models.ManyToManyField(blank=True, to='root.Tag')),
            ],
        ),
    ]
