# Generated by Django 4.0.1 on 2022-01-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_tag_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Post',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at']},
        ),
    ]
