# Generated by Django 4.0.1 on 2022-01-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_rename_article_post_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPost',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True)),
                ('meta_description', models.TextField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
