# Generated by Django 4.0.1 on 2022-01-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_specialpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpost',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.SlugField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_picture', models.URLField()),
                ('preview_image', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('links', models.JSONField()),
                ('speakers', models.ManyToManyField(to='root.Person')),
                ('tags', models.ManyToManyField(blank=True, to='root.Tag')),
            ],
        ),
    ]
